### ISSUE TITLE
Example Local Agent Configuration

### ISSUE THREAD

**Issue by jseiser** [mimacom/ansible-role-bamboo-agent#3]
Is it possible to demonstrate a local agent configuration?

Playbook
```
- hosts: local-bamboo-agent
  become: yes

  pre_tasks:
    - name: Ensure Apps Folder Exists
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - /apps
        - /apps/mvn

    - name: Maven 3.5.2
      unarchive:
        src: http://apache.claz.org/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
        dest: /apps/mvn
        remote_src: yes
        creates: /apps/mvn/apache-maven-3.2.5/bin/mvn

  tasks:
    - name: mimacom.bamboo-agent
      include_role:
        name: mimacom.bamboo-agent
      tags:
        - local_bamboo_agent
```

Group Var
```
install_jdk: false
bamboo_agent_remote: false
bamboo_master_user: bamboo
bamboo_agent_npmrc: ""
bamboo_agent_maven_settings: ""

bamboo_agent_capabilities:
    - name: http://apache.claz.org/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
      binary_path: /apps/mvn/apache-maven-3.2.5/bin
      symlinks: []
      properties: []
```

This is also using your bamboo role to actually install bamboo, then Im running this agent role against the same instance.  Playbook runs without error, but I have nothing showing in the agent configuration.
