### ISSUE TITLE
ERROR! The handlers/main.yml file for role 'mimacom.bamboo-agent' must contain a lt of tasks

### ISSUE THREAD

**Issue by GanimanSwift** [mimacom/ansible-role-bamboo-agent#7]
I've tried installing this role by:

```
ansible-galaxy install mimacom.bamboo-agent
```

and 

```
git clone https://github.com/mimacom/ansible-role-bamboo-agent.git ansible-bamboo-agent
```

My playbook is simple:
```
- hosts: bambooagent
  become: yes
  roles:
    - role: mimacom.bamboo-agent
      install_jdk: false
      bamboo_agent_remote: true
      bamboo_master_version: 6.6.1
      bamboo_master_fqdn: "bamboo.mysite.com"
      bamboo_master_https: true
      bamboo_master_port: 443
```

No matter what I try, I get the following error:

```
ERROR! The handlers/main.yml file for role 'mimacom.bamboo-agent' must contain a list of tasks

The error appears to have been in '/etc/ansible/roles/mimacom.bamboo-agent/tasks/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include: deprecated_bamboo_master.yml
^ here
```
